name: .NET CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore ./Marketplace/Marketplace.sln

    - name: Build Application
      run: dotnet build ./Marketplace/Marketplace.sln --configuration Release --no-restore